<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!--<PublishAot>true</PublishAot>-->
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lip.Connection\Lip.Connection.csproj" />
    <ProjectReference Include="..\Lip.Context\Lip.Context.csproj" />
    <ProjectReference Include="..\Lip.Core\Lip.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.0" />
    <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
    <PackageReference Include="System.IO.Abstractions.TestingHelpers" Version="21.2.1" />
  </ItemGroup>

</Project>
