site_name: Lip
site_url: https://docs.lippkg.com

nav:
  - Languages:
    - English: javascript:changeLanguage('en')
    - 中文: javascript:changeLanguage('zh')

  - Basics:
    - index.md
    - installation.md
    - quickstart.md
    - lipui_quickstart.md
    - creator_quickstart.md
    - faq.md
    - tooth_json_file_reference.md
    - Changelog: https://github.com/LipPkg/Lip/blob/main/CHANGELOG.md

  - Tutorials:
    - tutorials/create_a_lip_tooth.md
    - tutorials/create_a_tool.md
    - tutorials/submit_your_tooth_to_lip_registry.md

  - Commands:
    - commands/lip.md
    - commands/lip_autoremove.md
    - commands/lip_cache.md
    - commands/lip_cache_purge.md
    - commands/lip_exec.md
    - commands/lip_install.md
    - commands/lip_list.md
    - commands/lip_show.md
    - commands/lip_tooth.md
    - commands/lip_tooth_init.md
    - commands/lip_tooth_pack.md
    - commands/lip_uninstall.md

theme:
  name: readthedocs
extra_javascript:
  - js/script.js

use_directory_urls: false

plugins:
  - i18n:
      default_language: en
      languages:
        en:
          name: English
        zh:
          name: 中文
      nav_translations:
        zh:
          Basics: 基础
          Changelog: 更新日志
          Commands: 命令
          Languages: 语言
          Tutorials: 教程
