site_name: lip
repo_url: https://github.com/futrime/lip/

nav:
  - Home: index.md

  - install.md

  - quickstart.md

  - faq.md

  - Tutorials:
    - tutorials/create_a_lip_tooth.md

  - Reference:
    - reference/lip.md
    - reference/lip_cache.md
    - reference/lip_cache_purge.md
    - reference/lip_install.md
    - reference/lip_list.md
    - reference/lip_show.md
    - reference/lip_tooth.md
    - reference/lip_tooth_init.md
    - reference/lip_tooth_pack.md
    - reference/lip_uninstall.md
    - reference/tooth_json_file_reference.md

  - Packages: https://bedrinth.com

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  favicon: images/favicon.ico
  logo: images/logo.webp
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc
  - tables
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight:
      auto_title: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist

plugins:
  - i18n:
      languages:
        - locale: en
          default: true
          name: English

        - locale: zh
          name: 中文
          nav_translations:
            Home: 首页
            Tutorials: 教程
            Reference: 参考
            Packages: 包

  - search
