site_name: lip Docs
repo_url: https://github.com/futrime/lip

docs_dir: .
exclude_docs: |
  /mkdocs.yml
  /requirements.txt

nav:
  - User Guide:
    - user-guide/index.md
    - user-guide/getting-started.md
    - user-guide/installation.md
    - user-guide/basic-use.md
    - Topic Guides: []
    - Reference: []
    - Commands: []
  - Packaging Guide:
    - packaging-guide/index.md
  - Marketplace: https://bedrinth.com

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  favicon: img/favicon.ico
  logo: img/logo.webp
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc
  - tables
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight:
      auto_title: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist

plugins:
  - i18n:
      languages:
        - locale: en
          default: true
          name: English

        - locale: zh
          name: 中文
          nav_translations: {}

  - search
