name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
         go-version-file: src/go.mod
         cache: true
         cache-dependency-path: src/go.sum

      - name: Set up Go workspace
        run: go work init ./src

      - name: Build Lip
        run: go build -ldflags "-X 'github.com/liteldev/lip/context.VersionString=${{ github.ref_name }}'" -o ./build/lip.exe github.com/liteldev/lip

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: lip-0.0.0-${{ matrix.os }}-amd64
          path: build

  pack:
    name: Pack installer
    needs: build
    runs-on: windows-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: lip-0.0.0-windows-amd64

      - name: Set up NSIS workspace
        run:  |
          C:\msys64\usr\bin\wget.exe -q https://downloads.sourceforge.net/project/nsis/NSIS%203/3.07/nsis-3.07.zip -O nsis.zip
          C:\msys64\usr\bin\wget.exe -q https://downloads.sourceforge.net/project/nsis/NSIS%203/3.07/nsis-3.07-strlen_8192.zip -O nsis-strlen.zip
          unzip -q -o nsis.zip
          mv nsis-3.07 nsis-protable
          unzip -q -o nsis-strlen.zip -d nsis-strlen
          bash -c 'cp -rf ./nsis-strlen/* ./nsis-protable/'
          rm -r ./nsis-strlen
          $env:PATH = "$env:PATH;${{ github.workspace }}/nsis-protable"
          [Environment]::SetEnvironmentVariable("PATH", $env:PATH, [System.EnvironmentVariableTarget]::Machine)

      - name: Build Setup Program
        run: |
          mv ./lip.exe ./nsis/
          mv LICENSE ./nsis/LICENSE
          makensis.exe ./nsis/make_installer.nsi

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          path: nsis/lip-0.0.0-windows-amd64-setup.exe