on:
  pull_request:
    paths:
      - .github/workflows/build-docs.yml
      - docs/**
  push:
    paths:
      - .github/workflows/build-docs.yml
      - docs/**
  workflow_dispatch:

jobs:
  build-docs:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v5
        with:
          version: 10

      - uses: actions/setup-node@v6
        with:
          cache: pnpm
          cache-dependency-path: docs/pnpm-lock.yaml
          node-version: 24

      - working-directory: docs
        run: |
          pnpm install

      - working-directory: docs
        run: |
          pnpm build

      - uses: actions/upload-pages-artifact@v4
        with:
          path: docs/.vitepress/dist/

  deploy:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: build-docs
    runs-on: ubuntu-latest
    concurrency:
      group: pages
      cancel-in-progress: false
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      id-token: write
      pages: write
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
