on:
  pull_request:
    paths:
      - .github/workflows/build.yml
      - 'src/**'
      - 'tests/**'
  push:
    paths:
      - .github/workflows/build.yml
      - 'src/**'
      - 'tests/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.runs-on }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - runtime: linux-arm64
            runs-on: ubuntu-24.04-arm
          - runtime: linux-x64
            runs-on: ubuntu-latest
          - runtime: osx-arm64
            runs-on: macos-latest
          - runtime: osx-x64
            runs-on: macos-15-intel
          - runtime: win-arm64
            runs-on: windows-11-arm
          - runtime: win-x64
            runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10

      - shell: bash
        run: |
          dotnet publish src/Lip.Cli \
            -o bin \
            -r ${{ matrix.runtime }} \
            --no-self-contained \
            -p:DebugType=embedded

      - shell: bash
        run: |
          dotnet publish src/Lip.Daemon \
            -o bin \
            -r ${{ matrix.runtime }} \
            --no-self-contained \
            -p:DebugType=embedded

      - uses: actions/upload-artifact@v7
        with:
          name: lip-${{ github.sha }}-${{ matrix.runtime }}
          path: bin/

  check-style:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10

      - run: |
          dotnet format \
            --verify-no-changes

  test:
    runs-on: ${{ matrix.runs-on }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubuntu-24.04-arm
          - ubuntu-latest
          - macos-latest
          - macos-15-intel
          - windows-11-arm
          - windows-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10

      - run: |
          dotnet test
