name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    strategy:
      matrix:
        GOOS: [darwin, linux, openbsd, windows]
        GOARCH: [amd64, arm64]
        include:
          - GOOS: darwin
            output: lip
          - GOOS: linux
            output: lip
          - GOOS: openbsd
            output: lip
          - GOOS: windows
            output: lip.exe
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
         go-version-file: src/go.mod
         cache: true
         cache-dependency-path: src/go.sum

      - name: Set up Go workspace
        run: go work init ./src

      - name: Build Lip
        run: |
          export GOOS=${{ matrix.GOOS }}
          export GOARCH=${{ matrix.GOARCH }}
          go build -ldflags "-X 'github.com/liteldev/lip/context.VersionString=${{ github.ref_name }}' -s -w" -o ./build/${{ matrix.output }} github.com/liteldev/lip

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: lip-0.0.0-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
          path: build

  make-windows-setup-program:
    name: Make Windows setup program
    needs: build
    runs-on: windows-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: lip-0.0.0-windows-amd64

      - name: Set up NSIS
        run:  |
          C:\msys64\usr\bin\wget.exe -q https://downloads.sourceforge.net/project/nsis/NSIS%203/3.07/nsis-3.07.zip -O nsis.zip
          C:\msys64\usr\bin\wget.exe -q https://downloads.sourceforge.net/project/nsis/NSIS%203/3.07/nsis-3.07-strlen_8192.zip -O nsis-strlen.zip
          C:\msys64\usr\bin\wget.exe -q https://nsis.sourceforge.io/mediawiki/images/7/7f/EnVar_plugin.zip -O EnVar_plugin.zip
          unzip -q -o nsis.zip
          mv nsis-3.07 nsis-portable
          unzip -q -o nsis-strlen.zip -d nsis-portable
          unzip -q -o EnVar_plugin.zip -d nsis-portable

      - name: Build setup program
        run: |
          mv ./lip.exe ./nsis/
          mv ./LICENSE ./nsis/
          .\nsis-portable\makensis /DLIP_VERSION=${{ github.ref_name }} ./nsis/make_installer.nsi

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: lip-0.0.0-windows-amd64-setup
          path: nsis/lip-0.0.0-windows-amd64-setup.exe